---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  selector:
    component: zookeeper
    ensemble: zookeeper
    server-id: "1"
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  - name: peer
    port: 2888
    targetPort: 2888
  - name: election
    port: 3888
    targetPort: 3888
---
kind: Pod
apiVersion: v1
metadata:
  name: zookeeper-1
  labels:
    component: zookeeper
    ensemble: zookeeper
    server-id: "1"
spec:
  containers:
    - name: "server"
      image: "everpeace/zookeeper"
      env:
      - name: "SERVER_ID"
        value: "1"
      - name: "MAX_SERVERS"
        value: "1"
      - name: "ENSEMBLE_NAME"
        value: "zookeeper"
      ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  selector:
    component: kafka-broker
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kafka-broker
  name: kafka-broker
spec:
  containers:
  - name: kafka
    image: everpeace/kafka
    env:
    - name: ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka-broker:9092"
    - name: ZK_CONNECT
      value: "zookeeper:2181"
    ports:
    - containerPort: 9092
