---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  type: NodePort
  selector:
    component: zookeeper
    ensemble: zookeeper
    server-id: "1"
  ports:
  - name: client
    port: 2181
    targetPort: 2181
    nodePort: 30101
  - name: peer
    port: 2888
    targetPort: 2888
  - name: election
    port: 3888
    targetPort: 3888
---
kind: Pod
apiVersion: v1
metadata:
  name: zookeeper-1
  labels:
    component: zookeeper
    ensemble: zookeeper
    server-id: "1"
spec:
  containers:
    - name: "server"
      image: "everpeace/zookeeper"
      env:
      - name: "SERVER_ID"
        value: "1"
      - name: "MAX_SERVERS"
        value: "1"
      - name: "ENSEMBLE_NAME"
        value: "zookeeper"
      ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
spec:
  type: NodePort
  selector:
    component: kafka-broker
    broker-cluster: kafka
    broker-id: "1"
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
    nodePort: 30201

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kafka-broker
    broker-cluster: kafka
    broker-id: "1"
  name: kafka-broker-1
spec:
  containers:
  - name: kafka
    image: everpeace/kafka
    env:
    - name: ADVERTISED_LISTENERS
      value: "PLAINTEXT://192.168.99.102:30201"
    - name: ZK_CONNECT
      value: "zookeeper:2181"
    - name: BROKER_ID
      value: "1"
    ports:
    - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2
spec:
  type: NodePort
  selector:
    component: kafka-broker
    broker-cluster: kafka
    broker-id: "2"
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
    nodePort: 30202

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kafka-broker
    broker-cluster: kafka
    broker-id: "2"
  name: kafka-broker-2
spec:
  containers:
  - name: kafka
    image: everpeace/kafka
    env:
    - name: ADVERTISED_LISTENERS
      value: "PLAINTEXT://192.168.99.102:30202"
    - name: ZK_CONNECT
      value: "zookeeper:2181"
    - name: BROKER_ID
      value: "2"
    ports:
    - containerPort: 9092
